version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: currency_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: currency_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - currency_network

  app:
    build: .
    container_name: currency_app
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - currency_network
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/currency_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_LIQUIBASE_ENABLED: "true"

volumes:
  postgres_data:

networks:
  currency_network:
    driver: bridge